### ISSUE TITLE
Does not deal with existing extension well:

### ISSUE THREAD

**Issue by josegonzalez** [tuupola/slim-fake-mcrypt#1]
If ext-mcrypt is already installed, you get the following:

```
jose@mactaku:~/Sites/seatgeek/sg-android-artifacts git:master $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)             
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - remove ext-mcrypt 0|remove tuupola/slim-fake-mcrypt dev-master
    - don't install tuupola/slim-fake-mcrypt dev-master|remove ext-mcrypt 0
    - Installation request for ext-mcrypt == 0.0.0.0 -> satisfiable by ext-mcrypt[0].
    - Installation request for tuupola/slim-fake-mcrypt dev-master -> satisfiable by tuupola/slim-fake-mcrypt[dev-master].
```

Might be a composer issue

**Comment by tuupola** [comment]
Why would you want to use it together with ext-mcrypt?

**Comment by josegonzalez** [comment]
I don't. I want to use it in heroku where I don't have ext-mcrypt available
in my build pack, but do have it locally.

**Comment by tuupola** [comment]
Ah yes of course. I read through composer documentation but I cannot find any way to optionally install something. However it feels wrong that composer fails when it tries to install package whose dependency is already satisfied.
